apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
  labels:
    name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      name: app
      labels:
        name: app
    spec:
     containers:
      - name: app
        image: kalyanibambal97/crud-123:v10
        ports:
        - containerPort: 80


